add publish image workflow
eBay/sbom-scorecard pull request #31
Opened 2023-01-23 16:47 UTC by developer-guy

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

PTAL @justinabrahms 

_I've upgraded the dependency due to an issue: https://github.com/google/osv-scanner/issues/101_

2023-01-23 17:54 UTC, justinabrahms requested changes
Minor change request. Our workflows are based on releases, not tags

2023-01-23 17:54 UTC, justinabrahms commented on .github/workflows/image.yaml
> +      - 'v*'
```suggestion
on:
  workflow_dispatch:
  release:
    types: [created]
```

2023-01-24 07:16 UTC, developer-guy commented
here is working CI job: https://github.com/developer-guy/sbom-scorecard/actions/runs/3993846663/jobs/6850928162

2023-01-24 08:01 UTC, justinabrahms approved these changes

2023-01-26 22:32 UTC, merged